---
title: "hw2"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, include=FALSE}
library(tidyverse)
library(irr)
```
### 1.1
```{r}
zilo_data <- read_csv("hw2_1_zilo_class.csv")
head(zilo_data)
```

```{r}
zilo_data %>% 
  as_tibble() %>% 
  distinct(stimulus, stimulus_source) %>% 
  count(stimulus_source)
```
### 1.2

```{r}
zilo_data %>% 
  select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
  spread(key = s_id, value = class) ->
  zilo_data_short
head(zilo_data_short)
```
```{r}
agree(zilo_data_short[,-c(1:3)])
```
### 1.3
```{r}
zilo_data_2s <- zilo_data_short[,c(4, 14)]
kappa2(zilo_data_2s)
```

### 1.4
```{r}
kappam.fleiss(zilo_data_short[,-c(1:3)])
```
### 1.5
Суждения оценщиков полностью совпадают в 74.2 процентах случаев. Мера согласованности Каппа Коэна между разметчиками 7 и 11 равна приблизительно 0.73 при p-value меньше 0.05. Мера согласованности Каппа Фляйса между всеми разметчиками равна 0.853 при p-value меньше 0.05, что означает, что степень согласованности разметчиков можно назвать высокой. 

### 2.1
```{r}
verbs_data <- read_csv("hw2_2_verbs.csv")
head(verbs_data)
```

```{r}
verbs_data %>% 
  as_tibble() %>% 
  distinct(SubjectCode) %>%
  summarize(n=n())
```

### 2.2
```{r}

```

### 2.3
```{r}

```

### 2.4
```{r}

```